export const SPECIALIZATIONS = [
  "Cardiologist",
  "Dentist",
  "Dermatologist",
  "ENT Specialist",
  "Eye Specialist",
  "General Physician",
  "Gastroenterologist",
  "Neurologist",
  "Nephrologist",
  "Orthopedic Surgeon",
  "Pediatrician",
  "Psychiatrist",
  "Radiologist",
  "Skin & Hair Specialist",
  "Physiotherapist",
  "Urologist",
  "Gynecologist",
  "Oncologist",
  "Rheumatologist",
  "Pulmonologist",
  "Endocrinologist",
  "Hematologist",
  "Immunologist",
  "Infectious Disease Specialist"
];
